from make_occurrence_view import MakeOccurrenceView
from create_event_view import CreateEventView
from manage_vol_ops_view import ManageVolOpsView
from show_calendar_view import ShowCalendarView
from allocate_worker_view import AllocateWorkerView
from event_wizard_view import EventWizardView
from class_wizard_view import ClassWizardView
from manage_events_view import ManageEventsView
