from edit_template_view import EditTemplateView
from list_template_view import ListTemplateView
from mail_view import MailView
from mail_to_bidders_view import MailToBiddersView
from mail_to_person_view import MailToPersonView
